<br>

#### 0. 특정 함수에 대해 궁금할 때

In [1]:
# 이것은 주석(comment)입니다.

In [2]:
# Shift + Enter : 셀의 실행
# Shift + Tap : 함수 & 변수의 Docstring 확인

a = 3
print(a) 

3


In [3]:
print

# Tab : 자동완성 
# Shift + Tab : 함수의 Docstring(Document String)

<function print>

<br>

#### 1. 기초 데이터 타입

#### 정수형(integer)과 실수형(floats)

In [4]:
# x라는 "변수"를 선언(Declaration) & x라는 변수에 9라는 "값"을 할당(Assignment)

x = 9

# eqaul : == <- ex. x == 3
# unequal : != 

In [5]:
print(x)

9


In [6]:
type(x) # 데이터타입 == 자료형 == 데이터를 담는 그릇의 종류(이름)

# integer

int

In [ ]:
# x = x + 1

In [9]:
x + 1

10

In [10]:
x * 2

18

In [13]:
x ** 12 # 제곱 연산

282429536481

In [14]:
x / 2 # 몫 계산

4.5

In [15]:
x % 2 # 나머지

1

In [ ]:
x = x + 1
x

In [16]:
x += 1
x

10

In [17]:
x *= 2 # 곱하여 변수에 그대로 담기
x

20

In [1]:
y = 2.5

In [2]:
y

2.5

In [3]:
y

2.5

In [ ]:
실수 자료형
Real

Floating-point numbers == 부동소수점

6.25 
== 6.25 * 10 ** 0
== 62.5 * 10 ** (-1)
== 0.625 * 10 ** 1

In [4]:
type(y) # 어떤 타입일까요?

float

In [5]:
y

2.5

In [6]:
# y를 정수 자료형으로 바꾸려면?

y = int(y) # from float to integer
y

2

In [7]:
x = 9 

float(x) 

9.0

In [8]:
print(y, y+1, y*2, y**2)

2 3 4 4


#### 문자열 (string)

In [ ]:
문자열 변수
Character sequence (cf. SQL)

줄 String

In [28]:
s = 'Hello'

In [29]:
type(s)

str

In [30]:
len(s) # 길이를 영어로 하면? (앞 3글자)

5

In [34]:
x = str(x)
x.

'9'

In [32]:
type(s)

s. # 마침표 연산자

str

In [35]:
s.upper()

'HELLO'

In [36]:
s.lower() # 모두 소문자로

'hello'

In [38]:
# 파이썬 문자열 포매팅

print("My name is {} and my age is {}".format("Groot", 20))

My name is Groot and my age is 20


In [9]:
print("my name is {} and my age is {}".format("cs",28))

my name is cs and my age is 28


In [39]:
print("Hello" + " " + "world") # 문자열 합치기

Hello world


In [10]:
print("hello"+"cs")

hellocs


In [11]:
print("hello"+" "+"cs")

hello cs


In [12]:
temp = "Python"
temp[0]

'P'

In [13]:
name="changsu"
name[0]

'c'

In [ ]:
temp(!!!) : !!!를 x로 넘겨주면서 temp라는 이름의 함수를 실행한다.

temp[???] : temp라는 그룹형 변수에서 ???에 해당하는 멤버를 꺼낸다.

??? <- index number : str / list / tuple / numpy.array (수치행렬)
??? <- key : dict / pandas.DataFrame (정형데이터)

In [44]:
# index-slicing

temp[2]

't'

In [42]:
temp

'Python'

In [ ]:
0~100 
-> [0:25], [25:50], [50:75], [75:100]

1. ~이상 & ~이하 : 0~25, 25~50, 50~75, 75~100
2. ~이상 & ~미만 : 0~24, 25~49, 50~74, 75~99 <- 100

In [45]:
temp[0:4] # ~이상 & ~미만

'Pyth'

In [47]:
temp

'Python'

In [50]:
temp[:4]

'Pyth'

In [51]:
temp

'Python'

In [54]:
temp[-1]

'n'

In [14]:
temp = "Python is easy"
temp.split(' ') # str을 특정한 문자(기본값:여백)를 기준으로 잘라내어 list로 만들어줍니다. (이 때 기준이 되는 해당 문자는 삭제됩니다.)

['Python', 'is', 'easy']

In [15]:
temp = "Python is easy"
temp.split(' ') # 's'를 기준으로 자르려면?

['Python', 'is', 'easy']

In [59]:
temp = ['Python', 'is', 'easy']

'___'.join(temp)

'Python___is___easy'

In [60]:
' '.join(temp) # "Python is easy" 와 같이 합치려면?

'Python is easy'

In [61]:
x = 214

str(x) # Integer to string

'214'

In [64]:
x = '231'

int(x) * 3

693

#### 참/거짓 (bool)

In [68]:
x = 10
x == 10

True

In [65]:
t = True
f = False

In [66]:
type(t)

# Boolean(불린, 불리언) type

bool

In [69]:
print(t and f)

False


In [70]:
print(t or f)

True


In [71]:
print(not t)

False


<br>

#### 2. 함수 (function, method)

In [ ]:
y = f(x)

In [86]:
# 2개의 숫자를 외부로부터 받아 합친 값을 돌려주는 함수 add_nums 만들기

# 코드블록 <- def / if / for / while / with / class

sample_data = 10

def add_nums(num1, num2=5, additional_num): # Parameter (매개변수)
    result_pre = additional_num * 2
    result = num1 + num2
    return result # result 변수에 담긴 "값"이 return으로 나갑니다.

add_nums(2, 10, sample_data)

In [92]:
result_num = add_nums(2) # Argument (인자)
result_num

7

In [91]:
result # 함수의 Scope

NameError: name 'result' is not defined

In [88]:
print('pyt\nhon')

pyt
hon


In [90]:
print(123, end='___')
print(123, end='___')
print(123, end='___')

123___123___123___

In [93]:
# Quiz 1. 성과 이름을 받아 이름을 돌려주는 함수 name_creator 만들기

def name_creator(last, first):
    full_name = last + first
    return full_name

In [16]:
def name(a,b):
    result = a + b
    return result

In [17]:
name("그", "루트")

'그루트'

In [18]:
# Quiz 2. 다음 함수는 에러를 출력합니다. 어디를 고쳐야할까요?

def drink():
    beverage = "Coke"
    print(beverage)
    return beverage

In [19]:
result = drink()

Coke


In [20]:
type(result) 
# NoneType == None == Null == N/A(Not Available) == NaN(Not A number)
# == vacant(無)

str

In [107]:
radius = 10

area = 3.14 * radius ** 2

area

314.0

In [105]:
# Quiz 3. 원의 반지름을 받아 원의 넓이를 Return 해주는 함수 circle_area 만들기 (ㅠ = 3.14)

def circle_area(radius):
    
    area = 3.14 * radius ** 2
    
    return area

In [106]:
circle_area(10)

314.0

<br>

# 목요일 수업 시작

<br>

<br>

#### 3. 컨테이너 (다른 변수들을 담을 수 있는 자료형)
list, dict, tuple, set

#### 리스트 (list)

In [25]:
x = [3, 1, 2, 4, 6] # 리스트의 생성
x

[3, 1, 2, 4, 6]

In [26]:
x[0]

3

In [27]:
x[0:3] # [3, 1, 2] 를 출력하려면?

[3, 1, 2]

In [30]:
x[0:len(x)+1] # 1부터 끝까지?

[3, 1, 2, 4, 6]

In [31]:
x[-1] 

6

In [32]:
x.append("어머나") # 리스트 item 추가하기
x

[3, 1, 2, 4, 6, '어머나']

In [33]:
x.pop() # 기본적으로 리스트의 마지막 요소를 삭제하고 반환 (pop(n) -> index 기반으로 n번째 아이템을 삭제할 수도 있음)

'어머나'

In [7]:
x

[3, 1, 2, 4, 6]

In [147]:
# 리스트 아이템의 삭제 
# 1) 데이터의 순서/자리를 활용하여 삭제할 때 : del == index를 활용 (추천)
# 2) 데이터 값 자체를 활용하여 삭제할 때 : remove() == value를 활용
# 3) 삭제 후 삭제한 값을 리턴받아 활용해야할 때 : pop() == index를 활용

In [34]:
del x[0] # 삭제의 영어 단어 앞 3글자? 
x

[1, 2, 4, 6]

In [37]:
x.remove(4)
x

[1, 2, 6]

In [38]:
# 리스트 합치기
y = [3, 4, 5]
z = x + y # 쉽게 생각해보세요 :)
z

[1, 2, 6, 3, 4, 5]

In [39]:
# 리스트 정렬하기
z.sort()
z

[1, 2, 3, 4, 5, 6]

In [40]:
# 리스트 역으로 정렬하기
z.sort(reverse=True) # '거꾸로' 를 영어로 하면?
z

[6, 5, 4, 3, 2, 1]

#### 딕셔너리 (dict)

In [41]:
cage = {'Cat' : '야옹', 'Dog' : '멍멍'} # {key:value, key:value, ...}
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [42]:
cage['Cat'] # key 기반 호출

'야옹'

In [44]:
print('Pig' in cage) # key 유무 체크

False


In [45]:
cage['Pig'] = '꿀꿀' # dict에 새로운 item 추가하기
cage

{'Cat': '야옹', 'Dog': '멍멍', 'Pig': '꿀꿀'}

In [46]:
del cage['Pig'] # 삭제의 영어 단어 앞 3글자?
cage

{'Cat': '야옹', 'Dog': '멍멍'}

In [47]:
cage.keys()

dict_keys(['Cat', 'Dog'])

In [48]:
cage.values() # value들을 꺼내려면?

dict_values(['야옹', '멍멍'])

#### 튜플(tuple) 
값과 크기가 변하지 않음

In [49]:
t = (5, 6)
type(t)

tuple

In [50]:
t[0]

5

In [51]:
# 튜플이 사용되는 예시

def return_tuple(x, y):
    return x, y

In [52]:
what = return_tuple(3, 4)
what

(3, 4)

#### 집합(set)
중복을 허용하지 않음

In [53]:
s = {1, 2, 3, 3, 4, 4, 5} 
s

{1, 2, 3, 4, 5}

In [54]:
temp = [1, 2, 3, 3, 4, 4, 5]
temp

[1, 2, 3, 3, 4, 4, 5]

In [83]:
# 리스트 temp 에서 중복을 제거하고, 다시 리스트로 만드려면?

what = ?(?(temp))
what

[1, 2, 3, 4, 5]

<br>

#### 4. 조건문과 반복문
if, for, while

#### if

In [56]:
def check_price(lunch_price):
    
    price_label = ''
    
    if lunch_price > 10000:
        price_label = "프리미엄 도시락"
    elif lunch_price < 3000: 
        price_label = "저렴이 도시락"
    else: # 나머지 조건 모두 받기
        price_label = "무난무난 도시락"
        
    return price_label

In [58]:
check_price(17000)

'프리미엄 도시락'

In [59]:
cage = ['Cat', 'Dog', 'Tiger']

In [60]:
if 'Cat' in cage:  # Key 유무 체크
    print('야옹아 이리온')

야옹아 이리온


In [61]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [62]:
if 'Dog' in cage.keys(): # Key 유무 체크
    print('치와와는 언제와')

치와와는 언제와


#### for

In [63]:
nums = [1, 2, 3, 4, 5]

In [64]:
for number in nums:
    print(number)

1
2
3
4
5


In [66]:
cage = {'Cat': '야옹', 'Dog': '멍멍', 'Tiger': '어흥'}

In [69]:
for item in cage.items(): # values + keys = items
    print(item)

('Cat', '야옹')
('Dog', '멍멍')
('Tiger', '어흥')


In [70]:
# 숫자들의 리스트에서 1과 4가 연속으로 나오는 숫자 찾기

list_of_nums = [121142131512315, 1241561717265467, 153462615114151231, 1634263414616123, 15236172821568]
for num in list_of_nums:
    if '14' in str(num):
        print(num)

121142131512315
153462615114151231
1634263414616123


In [71]:
range(5) # '범위'를 영어로?

range(0, 5)

In [73]:
for index in range(6):
    print(index)

0
1
2
3
4
5


In [74]:
class_1 = ['철수', '영희', '동수'] 

In [75]:
for student in class_1:
    print("얘 이름은 {}래요".format(student))

얘 이름은 철수래요
얘 이름은 영희래요
얘 이름은 동수래요


In [76]:
# enumerate 배우기

for index, student in enumerate(class_1):
    print("얘 번호는 {}번이구요. 이름은 {}래요".format(index, student))

얘 번호는 0번이구요. 이름은 철수래요
얘 번호는 1번이구요. 이름은 영희래요
얘 번호는 2번이구요. 이름은 동수래요


In [7]:
# for 문의 주된 활용 방식

empty_list = []
for student in class_1:
    empty_list.append('김' + student) # 리스트에 item 추가하기

NameError: name 'class_1' is not defined

In [78]:
empty_list

['김철수', '김영희', '김동수']

#### while

In [79]:
temp = 1
while temp <= 10:
    print(temp)
    temp = temp + 1 # temp 를 1 증가시켜주려면?

1
2
3
4
5
6
7
8
9
10


In [107]:
# 무한 루프, Pass, Interrupting kernel

while True:
    pass

KeyboardInterrupt: 

In [1]:
idx = 0
while True:
    if idx >= 5:
        break
    else:
        print(idx)
        idx += 1

0
1
2
3
4


In [212]:
# Quiz 4. 점수(0~100)를 입력으로 받아 학점을 돌려주는 함수 grade를 만드세요.

In [80]:
def grade(a) :
    if a>90:
        result="A"
    elif a>80:
        result="B"
    elif a>70:
        result="C"
    else:
        result="F"
    return result

In [82]:
grade(97)

'A'

In [216]:
# Quiz 5. 3개의 숫자를 입력으로 받아, 가장 큰 수를 돌려주는 함수 best 를 만드세요. (Hint. 리스트와 sort()를 활용해보세요.)

In [92]:
def sort(a,b,c):
    k=[a,b,c]
    k.sort(reverse=True)
    return k[0]

In [95]:
sort(83, 56, 90)

90

In [251]:
# Quiz 6. 숫자 하나를 입력받아, 홀수면 "odd", 짝수면 "even"을 돌려주는 함수 odd_or_even을 만드세요. (나머지 연산 명령어는?)

In [253]:
odd_or_even(9)

odd


In [254]:
# Quiz 7. "20180323sunny" 와 같은 문자열을 입력받아, "Year is 2018, Day is 0323, Weather is sunny" 를 출력하는 함수 weather를 만드세요.

In [256]:
weather('20180323still cold')

Year is 2018, Day is 0323, Weather is still cold


<br>

#### 5. Python 기본 내장함수와 외장함수

In [97]:
len('Python') # 길이?

6

In [98]:
list('Python')

['P', 'y', 't', 'h', 'o', 'n']

In [99]:
abs(-1.2) # '절대값'의 앞 3글자

1.2

In [102]:
round(1.7) # 반올림

2

In [100]:
sum([1, 2, 3]) # 합

6

In [101]:
max([1, 2, 3]) # 최대값

3

In [103]:
min([1, 2, 3]) # 최소값

1

In [104]:
for i in range(0, 100, 10):
    print(i)

0
10
20
30
40
50
60
70
80
90


In [107]:
def func(x):
    return x ** 2

In [108]:
func(5)

25

In [109]:
# x(input) 를 받아 x**2(output) 를 return 해주는 람다 함수
func_2=lambda x:x**2


In [110]:
func_2(6)

36

In [324]:
func(5)

25

<br>

#### 6. 라이브러리 활용하기 (Library == Package, Module(단일 .py)의 상위 개념 )

In [20]:
%%writefile module_example.py

# @ module_example.py

def print_something() : 
    print('Hello world!')

def sum_nums(num1, num2) : 
    result = num1 + num2
    return result

Writing module_example.py


In [17]:
# %ls module_example.py

In [5]:
@ cmd

SyntaxError: incomplete input (4142314703.py, line 1)

In [6]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 34.0 MB/s eta 0:00:0000:0100:01


In [2]:
import module_example

module_example.print_something()

Hello world!


In [7]:
import numpy # import 라이브러리이름

In [8]:
a = numpy.array([1, 2, 3])
a

array([1, 2, 3])

In [9]:
import numpy as np # import 라이브러리이름 as 별명

In [10]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [11]:
from numpy import array, ndarray # from 라이브러리이름 import 함수이름

In [12]:
a = array([1, 2, 3])
a

array([1, 2, 3])

In [13]:
import random # 외장함수

x = random.random()
x

0.1793934127160216

In [16]:
x = random.randint(1, 100) # 1과 100 사이의 '정수' 를 랜덤하게 뽑으려면? Shift + Tab 을 활용해보세요!
x

18

In [17]:
for i in range(10):
    x=random.randint(1,100)
    print(x)

91
58
57
58
17
61
21
25
21
64


In [18]:
import os # 외장함수

os.getcwd() # get current working directory

'/Users/sinchangsu/Desktop/파이썬/기초교육원파이썬'

#### pip 명령어 살펴보기 : pip + [ list, show/install/uninstall/download library_name]

In [20]:
# cmd 에서 입력해 결과를 확인해보세요.

pip list

pip show numpy
pip install numpy (주의)
pip uninstall numpy (주의)

pip download django 

SyntaxError: invalid syntax (250050460.py, line 3)